### ISSUE TITLE
Coloured terminal output

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/QuickCheckVEngine#18]
It would be nice if the output included colour sequences so you can easily see the line that diverges without having to scan for ">" "<".

Might be easiest to use the [ansi-terminal](https://hackage.haskell.org/package/ansi-terminal) package to make error prints something like red/bold?

**Comment by PeterRugg** [comment]
Hopefully addressed by https://github.com/CTSRD-CHERI/QuickCheckVEngine/commit/fc7612a724f99d325a2eba7ae2fbe94f42bc1edd?

**Comment by arichardson** [comment]
Thanks! There are probably more places that could be made more readable using colours, but this is a huge improvement and fixes my main use-case :)
