### ISSUE TITLE
--continue-on-fail does nothing with --trace-directory

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/QuickCheckVEngine#22]
It would be useful to stop replaying traces once we hit a failure. Should be quite easy to implement by adding a check for `optContinueOnFail` here: https://github.com/CTSRD-CHERI/QuickCheckVEngine/blob/fd6e4f34c17a20197a1dccbaaa48663d5e95c098/src/QuickCheckVEngine/Main.hs#L342

Unfortunately I don't speak enough haskell to figure out how to do that idiomatically.

**Comment by PeterRugg** [comment]
Hopefully fixed by https://github.com/CTSRD-CHERI/QuickCheckVEngine/commit/95077dd91477dde4e287c47bc5f76a87191f67fc

**Comment by arichardson** [comment]
Confirmed that this fixes the issue. Thanks!
