### ISSUE TITLE
Need an option to avoid using HPM counter CSRs

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/QuickCheckVEngine#25]
When generating the all/random template we appear to end up with reads of HPM CSRs indices (I believe `rv32_zicsr` is where this comes from?) and those result in divergences vs sail. Would be good to have an option to explicitly avoid those CSR numbers for `has_ihpm == false`.

**Comment by PeterRugg** [comment]
Apologies, I started looking, but it seems they could come from multiple different sources. I'll dig into this more on Monday.
