### ISSUE TITLE
No disassembly for compressed instructions

### ISSUE THREAD

**Issue by francislaus** [CTSRD-CHERI/QuickCheckVEngine#46]
The function used for disassembling is not implemented: https://github.com/CTSRD-CHERI/QuickCheckVEngine/blob/cea1f331cf821f3e1590bf455062d28b19a67ce3/src/RISCV/RV_C.hs#L213-L215

**Comment by PeterRugg** [comment]
Addressed by https://github.com/CTSRD-CHERI/QuickCheckVEngine/pull/54. Thanks @elliotb-lowrisc! If people need any more elaborate compressed support, let's open more specific issues.
