### ISSUE TITLE
`c_flq` & `c_fsq` not in spec

### ISSUE THREAD

**Issue by elliotb-lowrisc** [CTSRD-CHERI/QuickCheckVEngine#53]
I can't find the `c_flq` and `c_fsq` instructions given in RV_C.hs ([added here](https://github.com/CTSRD-CHERI/QuickCheckVEngine/commit/11daa05db0712f529f0d855ef987d501ba849f07)) in the RISC-V "C" extension spec (20191213). The closest I can find is FLQ and FSQ in RV128Q, but there is no mention of a compressed version.

They seem to share the same encoding as the C.LQ and C.SQ RV128C instructions that are in the spec but not yet in RV_C.hs. Shall I put a PR together to change their names from `c_flq`/`c_fsq` to `c_lq`/`c_sq` in RV_C.hs?

**Comment by PeterRugg** [comment]
Hmm, this is very odd. I also can't see where they would have come from, and the encoding seems to clash with the c.fld and c.fsd instructions anyway... I don't know if @gameboo has any recollection, but it was a long time ago. I'd say let's make it match our current understanding as you suggest.

**Comment by elliotb-lowrisc** [comment]
Alright, I'll create a PR
