### ISSUE TITLE
Arguments of lw in GenMemory.hs are likely to be wrong

### ISSUE THREAD

**Issue by francislaus** [CTSRD-CHERI/QuickCheckVEngine#9]
The order of arguments of the lw instruction changed recently, but code in gen_pte_perms has not changed. When doing this it would be good to refactor the gen_pte_perms code such that it uses variables instead of integers.

**Comment by PeterRugg** [comment]
Is this still an issue?

**Comment by francislaus** [comment]
I cannot exactly remember, but I do not think so. I think it is ok to close and we can come back later if needed.
